{% set name = "onnxruntime" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/onnxruntime/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 671440949c55adbe0088c4b91d5738dca071a8e4f2e0fc37a8d802757f42ddbd
    patches:
      - 0001-Use-more-system-libraries.patch
  - url: https://github.com/onnx/onnx/archive/refs/tags/v1.10.1.zip
    sha256: ea664f36b86289ff5ce3f7643c5f05ec25b14d5a8c0e1ccd90828cf6399ca08c
    folder: onnx
  - url: https://gitlab.com/libeigen/eigen/-/archive/d10b27fe37736d2944630ecd7557cefa95cf87c9/eigen-d10b27fe37736d2944630ecd7557cefa95cf87c9.tar.gz
    sha256: a3c10a8c14f55e9f09f98b0a0ac6874c21bda91f65b7469d9b1f6925990e867b
    folder: eigen
  - url: https://github.com/pytorch/cpuinfo/archive/5916273f79a21551890fd3d56fc5375a78d1598d.zip
    sha256: 2a160c527d3c58085ce260f34f9e2b161adc009b34186a2baf24e74376e89e6d
    folder: pytorch_cpuinfo
  - url: https://github.com/nlohmann/json/archive/refs/tags/v3.9.1.tar.gz
    sha256: 4cf0df69731494668bdd6460ed8cb269b68de9c19ad8c27abc24cd72605b2d5b
    folder: json
build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - libprotobuf
  host:
    - python
    - pip
    - wheel
    - boost_mp11
    - flake8
    - flatbuffers
    - gmock
    - gtest
    - libdate
    - python-flatbuffers
    - re2
    - optional-lite
    - nsync
    - libprotobuf
    # We need to statically link protobuf until we link against a system libonnx
    # See: https://github.com/conda-forge/onnxruntime-feedstock/issues/5
    - libprotobuf-static
    - numpy
    - pybind11
    - safeint
  run:
    - python
    - python-flatbuffers
    - {{ pin_compatible('numpy') }}
    - protobuf

test:
  imports:
    - onnxruntime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/onnxruntime/
  summary: cross-platform, high performance ML inferencing and training accelerator
  license: MIT
  license_file:
    - LICENSE
    - cmake/external/onnx/LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
