{% set name = "onnxruntime" %}
{% set version = "1.11.1" %}


package:
  name: {{ name|lower }}{{ suffix }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/onnxruntime/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 307ba492dc6a35992ca561fa1c90ad919ed6bd40adef578a07725b5e88ccf633
    patches:
      - 0001_dont_vectorize.patch
  - url: https://github.com/onnx/onnx/archive/850a81b0b77786bf99ea90580242b084f86a6235.tar.gz
    sha256: 3b09259ec93b2b1d33e7321977038c4fd73eaac9fd0632765978f896da905f3f
    folder: onnx
  - url: https://gitlab.com/libeigen/eigen/-/archive/d10b27fe37736d2944630ecd7557cefa95cf87c9/eigen-d10b27fe37736d2944630ecd7557cefa95cf87c9.tar.gz
    sha256: a3c10a8c14f55e9f09f98b0a0ac6874c21bda91f65b7469d9b1f6925990e867b
    folder: eigen
  - url: https://github.com/pytorch/cpuinfo/archive/5916273f79a21551890fd3d56fc5375a78d1598d.zip
    sha256: 2a160c527d3c58085ce260f34f9e2b161adc009b34186a2baf24e74376e89e6d
    folder: pytorch_cpuinfo
  - url: https://github.com/nlohmann/json/archive/refs/tags/v3.9.1.tar.gz
    sha256: 4cf0df69731494668bdd6460ed8cb269b68de9c19ad8c27abc24cd72605b2d5b
    folder: json
build:
  number: 2
  skip: true  # [win]
  # Since 1.11, power9 seems to be required.
  skip: true  # [ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - libprotobuf
  host:
    - python
    - pip
    - wheel
    - boost_mp11
    - flake8
    - flatbuffers !=2.0.6
    - gmock
    - gtest
    - libdate
    - python-flatbuffers
    - re2
    - optional-lite
    - nsync
    - libprotobuf
    # We need to statically link protobuf until we link against a system libonnx
    # See: https://github.com/conda-forge/onnxruntime-feedstock/issues/5
    - libprotobuf-static
    - numpy
    - pybind11
    - safeint
  run:
    - python
    - python-flatbuffers
    - {{ pin_compatible('numpy') }}
    - protobuf
  run_constrained:
    - onnxruntime <0a0  # [suffix == "-novec"]

test:
  imports:
    - onnxruntime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/onnxruntime/
  summary: cross-platform, high performance ML inferencing and training accelerator
  license: MIT
  license_file:
    - LICENSE
    - cmake/external/onnx/LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
    - jtilly
