{% set name = "onnxruntime" %}
{% set cuda_enabled = cuda_compiler_version != "None" %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}{{ suffix }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/onnxruntime/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 93a9b6f148639938ccbaa48d0f641d8f33312fdfcc69ee9466e11362b43917c4
    patches:
      - never_call_install_python_deps.patch
      # Workaround for https://github.com/conda-forge/onnxruntime-feedstock/pull/56#issuecomment-1586080419
      - windows_workaround_conflict_onnxruntime_dll_system32.patch  # [win]
      - 16337.patch
      # Temporary fix for CUDA compilation, see https://github.com/microsoft/onnxruntime/issues/16000#issuecomment-1562265152
      # this can be removed once we bump to 1.16 release
      - fix_missing_cuda_definition.patch
      # Workaround for https://github.com/microsoft/onnxruntime/issues/13225
      - comment_InterThreadPoolWithDenormalAsZero.patch  # [osx]


build:
  number: 2
  # Since 1.11, power9 seems to be required.
  skip: true  # [ppc64le or (cuda_compiler_version == "10.2" or cuda_compiler_version == "11.0" or cuda_compiler_version == "11.1")]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
  ignore_run_exports_from:
    - zlib
  # This needs to be coherent with the entry_points list defined around
  # https://github.com/microsoft/onnxruntime/blob/main/setup.py#L735
  entry_points:
    - onnxruntime_test = onnxruntime.tools.onnxruntime_test:main
  track_features:
    {{ "- onnxruntime-cuda" if cuda_enabled else "" }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy 1.21.6                           # [(build_platform != target_platform) and py<310]
    - numpy                                  # [(build_platform != target_platform) and py>=310]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - cmake
    - ninja
    # we need protoc in the build environment for cross compilations
    - libprotobuf 3.21
  host:
    - python
    - pip
    - wheel
    - cudnn  # [cuda_compiler_version != "None"]
    - flake8
    - gmock
    - libdate
    - packaging
    - python-flatbuffers
    - optional-lite
    - zlib
    - numpy 1.21.6  # [py<310]
    - numpy         # [py>=310]
    - pybind11
  run:
    - coloredlogs
    - packaging
    - protobuf
    - python
    - python-flatbuffers
    - sympy
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - onnxruntime <0a0  # [suffix == "-novec"]

test:
  imports:
    - onnxruntime
  commands:
    - pip check
    - onnxruntime_test --help
  requires:
    - pip

outputs:
  - name: {{ name|lower }}{{ suffix }}
  - name: {{ name|lower }}{{ suffix }}-cpp
    script: install-cpp.sh  # [unix]
    script: install-cpp.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      run_constrained:
        - onnxruntime-cpp <0a0  # [suffix == "-novec"]
    test:
      requires:
        - {{ compiler('cxx') }}
        - sysroot_linux-64 2.17  # [linux64 and cdt_name!='cos6']
      files:
        - test.cpp
        - run_cpp_test.bat  # [win]
      commands:
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime test.cpp                               # [linux]
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime -Wl,-rpath,$CONDA_PREFIX/lib test.cpp  # [osx]
        - ./a.out  # [unix]
        - call .\run_cpp_test.bat  # [win]

about:
  home: https://github.com/microsoft/onnxruntime/
  summary: cross-platform, high performance ML inferencing and training accelerator
  license: MIT AND BSL-1.0  # mp11 is BSL 1.0
  license_file:
    - LICENSE
    - build-ci/Release/_deps/abseil_cpp-src/LICENSE
    - build-ci/Release/_deps/date-src/LICENSE.txt
    - build-ci/Release/_deps/eigen-src/COPYING.MPL2
    - build-ci/Release/_deps/flatbuffers-src/LICENSE.txt
    - build-ci/Release/_deps/google_nsync-src/LICENSE  # [not win]
    - build-ci/Release/_deps/gsl-src/LICENSE
    - build-ci/Release/_deps/microsoft_wil-src/LICENSE
    - build-ci/Release/_deps/nlohmann_json-src/LICENSE.MIT
    - build-ci/Release/_deps/onnx-src/LICENSE
    - build-ci/Release/_deps/protobuf-src/LICENSE
    - build-ci/Release/_deps/pytorch_cpuinfo-src/LICENSE
    - build-ci/Release/_deps/re2-src/LICENSE
    - build-ci/Release/_deps/safeint-src/LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
    - jtilly
    - cbourjau
