{% set name = "onnxruntime" %}
{% set cuda_enabled = cuda_compiler_version != "None" %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}
{% set version = "1.17.1" %}
{% set suffix = "" %}  # [suffix == None] # help the linter

package:
  name: {{ name|lower }}{{ suffix }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/onnxruntime/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 88335a1ccbccccb35d5d3aaadee090a9745cf90d97ca87c4a3ac5c4b694b7b17
    patches:
      - never_call_install_python_deps.patch
      # Workaround for https://github.com/conda-forge/onnxruntime-feedstock/pull/56#issuecomment-1586080419
      - windows_workaround_conflict_onnxruntime_dll_system32.patch  # [win]
      # Workaround for https://github.com/microsoft/onnxruntime/issues/13225
      - comment_InterThreadPoolWithDenormalAsZero.patch  # [osx]


build:
  number: 0
  # Since 1.11, power9 seems to be required.
  skip: true  # [ppc64le]
  # CUDA compilation for Windows goes out-of-memory.
  skip: true  # [win and cuda_compiler_version in ("11.2", "11.8", "12.0")]
  skip: true  # [linux and aarch64 and cuda_compiler_version == "12.0"]
  skip: true  # [cuda_compiler_version == "11.2"]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
  ignore_run_exports_from:
    - zlib
  # This needs to be coherent with the entry_points list defined around
  # https://github.com/microsoft/onnxruntime/blob/main/setup.py#L735
  entry_points:
    - onnxruntime_test = onnxruntime.tools.onnxruntime_test:main
  track_features: 
    {{ "- onnxruntime-cuda" if cuda_enabled else "" }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
    - cmake
    - ninja
    # we need protoc in the build environment for cross compilations
    - libprotobuf 3.21
  host:
    - python
    - pip
    - wheel
    - cudnn                                     # [cuda_compiler_version != "None"]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - flake8
    - gmock
    - libdate
    - packaging
    - python-flatbuffers
    - optional-lite
    - zlib
    - numpy
    - pybind11
  run:
    - coloredlogs
    - packaging
    - protobuf
    - python
    - python-flatbuffers
    - sympy
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - onnxruntime <0a0  # [suffix == "-novec"]

test:
  imports:
    - onnxruntime
  commands:
    - pip check
    - onnxruntime_test --help
  requires:
    - pip

outputs:
  - name: {{ name|lower }}{{ suffix }}
  - name: {{ name|lower }}{{ suffix }}-cpp
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}
      run_exports:
        - {{ pin_subpackage((name|lower) + suffix + '-cpp', max_pin='x.x.x') }}
    script: install-cpp.sh  # [unix]
    script: install-cpp.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler("cuda") }}  # [cuda_compiler_version != "None"]
      run:
        - __cuda    # [cuda_compiler_version != "None"]
      run_constrained:
        - onnxruntime-cpp <0a0  # [suffix == "-novec"]
    test:
      requires:
        - {{ compiler('cxx') }}
        - sysroot_linux-64 2.17  # [linux64 and cdt_name!='cos6']
      files:
        - test.cpp
        - run_cpp_test.bat  # [win]
      commands:
        - test -f $PREFIX/include/onnxruntime/core/session/onnxruntime_cxx_api.h  # [unix]
        - test -f $PREFIX/lib/libonnxruntime${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libonnxruntime_providers_shared${SHLIB_EXT}  # [unix and cuda_compiler_version != "None"]
        - test -f $PREFIX/lib/libonnxruntime_providers_cuda${SHLIB_EXT}  # [unix and cuda_compiler_version != "None"]
        - if not exist %LIBRARY_INC%\\onnxruntime\\core\\session\\onnxruntime_cxx_api.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\onnxruntime_conda.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\onnxruntime_conda.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\onnxruntime_providers_shared.lib exit 1  # [win and cuda_compiler_version != "None"]
        - if not exist %LIBRARY_BIN%\\onnxruntime_providers_shared.dll exit 1  # [win and cuda_compiler_version != "None"]
        - if not exist %LIBRARY_LIB%\\onnxruntime_providers_cuda.lib exit 1  # [win and cuda_compiler_version != "None"]
        - if not exist %LIBRARY_BIN%\\onnxruntime_providers_cuda.dll exit 1  # [win and cuda_compiler_version != "None"]
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime test.cpp                               # [linux]
        - $CXX $CXXFLAGS -I$PREFIX/include/ -L$PREFIX/lib/ -lonnxruntime -Wl,-rpath,$CONDA_PREFIX/lib test.cpp  # [osx]
        - ./a.out  # [unix]
        - call .\run_cpp_test.bat  # [win]

about:
  home: https://github.com/microsoft/onnxruntime/
  summary: cross-platform, high performance ML inferencing and training accelerator
  license: MIT AND BSL-1.0  # mp11 is BSL 1.0
  license_file:
    - LICENSE
    - build-ci/Release/_deps/abseil_cpp-src/LICENSE
    - build-ci/Release/_deps/eigen-src/COPYING.MPL2
    - build-ci/Release/_deps/flatbuffers-src/LICENSE.txt
    - build-ci/Release/_deps/google_nsync-src/LICENSE  # [not win]
    - build-ci/Release/_deps/gsl-src/LICENSE
    - build-ci/Release/_deps/nlohmann_json-src/LICENSE.MIT
    - build-ci/Release/_deps/onnx-src/LICENSE
    - build-ci/Release/_deps/protobuf-src/LICENSE
    - build-ci/Release/_deps/pytorch_cpuinfo-src/LICENSE
    - build-ci/Release/_deps/re2-src/LICENSE
    - build-ci/Release/_deps/safeint-src/LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
    - jtilly
    - cbourjau
