build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
test_on_native_only: true
azure:
  #variables:
  #    CONDA_BLD_PATH: "C:\\bld\\"
  settings_win:
      pool:
          vmImage: windows-2019
