azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 10GiB
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld\
      MINIFORGE_HOME: C:\Miniforge
      SET_PAGEFILE: 'True'
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_build_tool: conda-build+conda-libmamba-solver
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
  linux_64: github_actions
  win_64: github_actions
test: native_and_emulated
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request

