build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  timeout_minutes: 720
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
  linux_aarch64: github_actions
  win_64: github_actions
  osx_arm64: github_actions
test: native_and_emulated
workflow_settings:
  build_workspace_dir:
  - provider: azure
    os: win
    value: C:\bld\
  free_disk_space:
  - provider: azure
    value: quick
  pagefile_size:
  - provider: azure
    os: linux
    value: 10
  - provider: azure
    os: win
    value: 16
  tools_install_dir:
  - provider: azure
    os: win
    value: C:\Miniforge
